import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowLeft, ArrowRight, Search, Check, Clock3, FileText, Layers3, ChevronRight, ExternalLink, Download, AlertCircle, Radio, Fingerprint, BookOpen, GitBranch } from 'lucide-react';
import './style.css';

type Stage = {id:string;title:string;status:string;count:number};
type Source = {id:string;url:string;title:string;characters:number;body_sha256:string;captured_at:string|null;excerpt:string;excerpt_truncated:boolean;supplemented:boolean};
type Task = {id:string;title:string;type:string;status:string;created_at:string|null;rules:string;fine_print:string;run_id:string;run_url:string;question_url:string;input_sha256:string;record_scope:string;warning:string;stages:Stage[];plan:{id:string;condition:string;priority:string;query:string}[];searches:{channel:string;query:string;role:string;status:string;results:{url:string;title:string;snippet:string}[]}[];sources:Source[];fetches:{url:string;status:string;error:string}[];supplement:{tool:string;url:string;status:string;error:string}[];forecast:Record<string,unknown>;analysis:{model:string;status:string;routing:Record<string,unknown>;gaps:unknown[];first_probability_yes:number|null};delivery:{status:string;note:string};usage:Record<string,number|null>};
type Data = {release:string;release_commit:string;generated_at:string;notice:string;tasks:Task[]};
const names:Record<string,string>={binary:'Binary',numeric:'Numeric',multiple_choice:'Multiple choice',discrete:'Discrete',date:'Date'};
const human=(v:string)=>v.replaceAll('_',' ');
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;
function summary(t:Task){const p=t.forecast.probability_yes;if(typeof p==='number')return pct(p)+' YES';const bins=t.forecast.option_probabilities||t.forecast.probabilities;if(bins&&typeof bins==='object'){const sorted=Object.entries(bins as Record<string,number>).sort((a,b)=>b[1]-a[1]);return sorted.length?`${pct(sorted[0][1])} · ${sorted[0][0]}`:'Distribution';}return Object.keys(t.forecast).length?'Distribution saved':'No forecast';}
function download(data:unknown,name:string){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
function Badge({value}:{value:string}){return <span className={`badge ${value.includes('gap')?'amber':value==='not_recorded'?'muted':'green'}`}><span/> {human(value)}</span>;}
function App(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(new URLSearchParams(location.search).get('question')),[view,setView]=useState('Research'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[stage,setStage]=useState('rules');
 useEffect(()=>{fetch(`${import.meta.env?.BASE_URL || '/'}data/console.json`).then(r=>{if(!r.ok)throw Error('Snapshot could not be loaded');return r.json();}).then(setData).catch(e=>setError(e.message));},[]);
 useEffect(()=>{const onPop=()=>setSelected(new URLSearchParams(location.search).get('question'));window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
 function open(id:string|null){setSelected(id);setStage('rules');const u=new URL(location.href);id?u.searchParams.set('question',id):u.searchParams.delete('question');history.pushState({},'',u);window.scrollTo(0,0);}
 if(error)return <div className="load"><AlertCircle/><h1>Snapshot unavailable</h1><p>{error}</p><button onClick={()=>location.reload()}>Retry</button></div>;
 if(!data)return <div className="load"><Layers3/><p>Loading the research archive…</p></div>;
 const task=data.tasks.find(t=>t.id===selected);const tasks=data.tasks.filter(t=>(filter==='all'||t.type===filter)&&(t.title+' '+t.id).toLowerCase().includes(query.toLowerCase()));
 return <><header className="header"><a className="brand" href="?" onClick={e=>{e.preventDefault();open(null);}}><span className="brand-icon"><Layers3 size={21}/></span>Forecast<span>Agent</span><small>RESEARCH CONSOLE</small></a><nav>{['Overview','Research','Activity'].map(v=><button key={v} className={view===v&&!task?'active':''} onClick={()=>{setView(v);open(null);}}>{v}</button>)}</nav><div className="header-right"><span className="release"><GitBranch size={13}/>v{data.release}</span><a href="https://github.com/chenencc/futureeval-forecasting-agent" target="_blank" rel="noreferrer">Repository <ArrowUpRight size={15}/></a></div></header>
 <div className="archive-bar"><span><Radio size={13}/> ARCHIVED SNAPSHOT</span><p>Real research records. Read-only preview · no live submission controls.</p><time>{new Date(data.generated_at).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</time></div>
 {task?<main className="detail"><button className="back" onClick={()=>open(null)}><ArrowLeft size={15}/> All research</button><div className="detail-heading"><div><div className="eyebrow">METACULUS / {names[task.type]||task.type} / #{task.id}</div><h1>{task.title}</h1><div className="heading-meta"><Badge value={task.status}/><span>Run {task.run_id}</span><a href={task.question_url} target="_blank" rel="noreferrer">Original question <ArrowUpRight size={14}/></a></div></div><button className="outline" onClick={()=>download(task,`question-${task.id}.json`)}><Download size={15}/> Export record</button></div>
 <div className="detail-grid"><aside className="steps"><div className="eyebrow">RESEARCH TRAIL</div>{task.stages.map((s,i)=><button key={s.id} onClick={()=>setStage(s.id)} className={stage===s.id?'selected':''}><span className={`step-icon ${s.status==='not_recorded'?'empty':''}`}>{s.status==='not_recorded'?<Clock3 size={13}/>:<Check size={13}/>}</span><span><small>0{i+1}</small>{s.title}</span><ChevronRight size={13}/></button>)}<div className="trail-note"><Fingerprint size={16}/><p>Every displayed source is linked to a saved body hash. A saved page is not a verified fact.</p></div></aside>
 <section className="stage-panel"><div className="panel-heading"><span className="eyebrow">STEP 0{task.stages.findIndex(s=>s.id===stage)+1}</span><Badge value={task.stages.find(s=>s.id===stage)!.status}/><h2>{task.stages.find(s=>s.id===stage)!.title}</h2></div>
 {stage==='rules'&&<><h3>Resolution criteria</h3><p className="prose">{task.rules}</p>{task.fine_print&&<><h3>Fine print</h3><p className="prose">{task.fine_print}</p></>}<div className="callout"><BookOpen size={18}/><p>The target event, observation date and resolution source belong to the question rules. Capture dates and publication dates are separate.</p></div></>}
 {stage==='plan'&&<>{task.plan.length?task.plan.map((p,i)=><article className="item" key={i}><div><span className="mono">NEED {p.id}</span><span className="tag">{p.priority||'Unspecified'}</span></div><h3>{p.condition}</h3>{p.query&&<p className="quote">{p.query}</p>}</article>):<Empty/>}</>}
 {stage==='search'&&<>{task.searches.length?task.searches.map((s,i)=><article className="item" key={i}><div><span className="tag">{s.channel}</span><Badge value={s.status}/></div><h3>{s.query}</h3><p className="subtle">Search role: {s.role} · {s.results.length} saved results</p>{s.results.map((r,j)=><a className="search-hit" key={j} href={r.url} target="_blank" rel="noreferrer"><span>{r.title||r.url}<ExternalLink size={12}/></span><small>{r.snippet}</small></a>)}</article>):<Empty/>}</>}
 {stage==='read'&&<><p className="subtle">{task.sources.length} saved bodies. Previews are bounded; omissions do not prove absence.</p>{task.sources.map(s=><SourceCard key={s.id} source={s}/>)}<h3>Fetch journal</h3>{task.fetches.map((f,i)=><div className="journal" key={i}><span>{f.url||'URL not recorded'}</span><Badge value={f.status}/>{f.error&&<p>{f.error}</p>}</div>)}</>}
 {stage==='supplement'&&<>{task.supplement.length?task.supplement.map((s,i)=><div className="journal" key={i}><span>{s.tool} · {s.url||'No URL recorded'}</span><Badge value={s.status||'unknown'}/>{s.error&&<p>{s.error}</p>}</div>):<Empty text="Supplement lineage exists in some archives, but no per-attempt journal is present in this export."/>}<p className="subtle">Supplemented bodies remain available in Read original sources.</p></>}
 {stage==='analysis'&&<><div className="model-card"><span className="brand-icon"><Layers3 size={20}/></span><div><strong>Mercury Decide</strong><p>{task.analysis.model}</p></div><Badge value={task.analysis.status}/></div><h3>Conditional rereading</h3><p className="prose">{task.analysis.routing.second_call_required?'A second decision was requested after reading additional saved original evidence.':'No second-call requirement is recorded.'}</p><pre>{JSON.stringify(task.analysis.routing,null,2)}</pre><h3>Remaining diagnostic gaps</h3>{task.analysis.gaps.length?<div className="gap-list">{task.analysis.gaps.map((g,i)=><span key={i}><AlertCircle size={14}/>{typeof g==='string'?human(g):JSON.stringify(g)}</span>)}</div>:<p className="subtle">No diagnostic gaps recorded. This does not establish factual correctness.</p>}</>}
 {stage==='forecast'&&<Forecast task={task}/>}
 {stage==='delivery'&&<><Empty text={task.delivery.note}/><div className="callout"><AlertCircle size={18}/><p>An analysis result is not a submission receipt. These archived experiments are not displayed as delivered forecasts.</p></div></>}
 </section><aside className="facts"><div className="fact-card"><div className="eyebrow">SAVED FORECAST</div><strong className="forecast-number">{summary(task)}</strong><span className="subtle">{names[task.type]||task.type} · archived decision</span><button onClick={()=>setStage('forecast')}>Explore distribution <ArrowRight size={14}/></button></div><div className="fact-card"><div className="eyebrow">RESOURCE JOURNAL</div><dl><dt>Search attempts</dt><dd>{task.usage.search_attempts}</dd><dt>Fetch attempts</dt><dd>{task.usage.fetch_attempts}</dd><dt>Acquisition model HTTP</dt><dd>{task.usage.acquisition_http_attempts}</dd><dt>Reported tokens</dt><dd>Not exported</dd></dl></div><div className="fact-card"><div className="eyebrow">PROVENANCE</div><a href={task.run_url} target="_blank" rel="noreferrer">Actions run <ArrowUpRight size={14}/></a><p className="subtle">{task.record_scope}</p><span className="mono hash">INPUT SHA256<br/>{task.input_sha256}</span></div></aside></div></main>:<main className="landing"><section className="hero"><div><div className="eyebrow"><span className="live-dot"/> FORECASTING, WITH A PAPER TRAIL</div><h1>Every forecast<br/>has a <em>trail.</em></h1><p>From the first search to the final distribution.<br/>Explore the evidence, decisions and gaps behind every question.</p><button className="primary" onClick={()=>open(data.tasks[0].id)}>Explore a research trail <ArrowUpRight size={17}/></button><span className="hero-note">Release {data.release} · archived evidence · source-linked</span></div><div className="hero-card"><div className="hero-card-top"><span><span className="live-dot"/> RESEARCH SPOTLIGHT</span><FileText size={17}/></div><div className="eyebrow">METACULUS · {names[data.tasks[0].type]}</div><h2>{data.tasks[0].title}</h2><div className="hero-prediction"><span>SAVED MODEL FORECAST</span><strong>{summary(data.tasks[0])}</strong></div><div className="mini-trail"><span><Check size={12}/> Evidence saved</span><span><Check size={12}/> Mercury reread</span><span className="amber-text"><AlertCircle size={12}/> Gaps visible</span></div><button onClick={()=>open(data.tasks[0].id)}>Follow the evidence <ArrowRight size={16}/></button></div></section>
 <section className="stats"><div><span>QUESTIONS IN THIS EXPORT</span><strong>{data.tasks.length.toString().padStart(2,'0')}</strong><small>Unique archived questions</small></div><div><span>SAVED SOURCE BODIES</span><strong>{data.tasks.reduce((n,t)=>n+t.sources.length,0)}</strong><small>Preserved with SHA256</small></div><div><span>WITH RECORDED GAPS</span><strong>{data.tasks.filter(t=>t.status.includes('gap')).length.toString().padStart(2,'0')}</strong><small>Shown, never concealed</small></div><div><span>RELEASE BASELINE</span><strong className="release-stat">v{data.release}</strong><small>{data.release_commit.slice(0,7)} · read-only console</small></div></section>
 {view==='Activity'?<section className="research"><div className="section-heading"><div><div className="eyebrow">ARCHIVED EXECUTIONS</div><h2>Activity & provenance</h2></div></div>{data.tasks.map(t=><div className="activity" key={t.id}><span className="step-icon"><FileText size={14}/></span><div><strong>{t.title}</strong><p>#{t.id} · Run {t.run_id} · {t.created_at||'Capture time not recorded'}</p></div><a href={t.run_url} target="_blank" rel="noreferrer">View run <ArrowUpRight size={14}/></a></div>)}</section>:<section className="research" id="research"><div className="section-heading"><div><div className="eyebrow">THE RESEARCH LIBRARY</div><h2>{view==='Overview'?'A view into the engine':'Questions, cited to source.'}</h2></div><button className="text-button" onClick={()=>download(data,'forecastagent-export.json')}><Download size={14}/> Export snapshot</button></div><div className="filters"><div className="filter-tabs">{['all','binary','numeric','multiple_choice','discrete','date'].map(f=><button className={filter===f?'selected':''} key={f} onClick={()=>setFilter(f)}>{f==='all'?'All questions':names[f]}</button>)}</div><label className="search"><Search size={16}/><input placeholder="Search questions or ID" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="table-head"><span>QUESTION / TYPE</span><span>EVIDENCE</span><span>FORECAST</span><span>STATUS</span></div>{tasks.length?tasks.map(t=><button className="question-row" key={t.id} onClick={()=>open(t.id)}><div><small>{names[t.type]||t.type} <span>#{t.id}</span></small><h3>{t.title}</h3></div><div className="row-source"><FileText size={14}/>{t.sources.length} sources<small>{t.searches.length} searches</small></div><strong className="row-forecast">{summary(t)}</strong><div><Badge value={t.status}/><ArrowUpRight className="row-arrow" size={17}/></div></button>):<Empty text="No questions match this filter."/>}</section>}
 <section className="workflow-strip"><div><span className="eyebrow">THE RELEASE 1.0.1 PIPELINE</span><h2>Open the steps.<br/>Inspect the evidence.</h2></div>{[['01','Original acquisition','Search, read and preserve.'],['02','Independent supplement','Fill gaps with saved provenance.'],['03','Mercury decision','Read originals. Reread if needed.'],['04','Validated delivery','Only a read-back receipt confirms delivery.']].map(([n,title,text])=><div key={n}><span className="mono">{n}</span><h3>{title}</h3><p>{text}</p></div>)}</section></main>}
 <footer><div className="brand"><Layers3 size={19}/>ForecastAgent</div><p>Evidence first. Uncertainty visible.</p><span>Archived preview · {data.tasks.length} questions · v{data.release}</span></footer></>;
}
function Empty({text='No record is available for this stage.'}:{text?:string}){return <div className="empty-state"><Clock3 size={24}/><h3>Not recorded</h3><p>{text}</p></div>;}
function SourceCard({source:s}:{source:Source}){return <details className="source-card"><summary><span className="source-id">{s.id}</span><div><strong>{s.title}</strong><small>{s.characters.toLocaleString()} characters · {s.supplemented?'supplemented':'saved body'}</small></div><ChevronRight size={16}/></summary><div className="source-content"><a href={s.url} target="_blank" rel="noreferrer">Open publisher page <ExternalLink size={13}/></a><p className="subtle">Capture time: {s.captured_at||'Not recorded'} · Current page may differ from the snapshot.</p><pre>{s.excerpt}</pre>{s.excerpt_truncated&&<p className="subtle">Preview truncated at 1,800 characters. The saved body is longer.</p>}<div className="hash mono">BODY SHA256 · {s.body_sha256}</div></div></details>;}
function Forecast({task:t}:{task:Task}){const f=t.forecast;const p=f.probability_yes;const choices=(f.option_probabilities||f.probabilities||f.bin_probabilities) as Record<string,number>|undefined;const knots=f.cdf_knots as [number,number][]|undefined;return <><div className="forecast-display"><span className="eyebrow">ARCHIVED FORECAST · {names[t.type]}</span><strong>{summary(t)}</strong><p>Forecast output is shown as saved. No probability is inferred from missing records.</p></div>{typeof p==='number'&&<><div className="probability-track"><span style={{width:`${p*100}%`}}/></div><div className="probability-label"><span>YES {pct(p)}</span><span>NO {pct(1-p)}</span></div></>}{choices&&<div className="distribution">{Object.entries(choices).map(([label,value])=><div key={label}><span>{label}</span><div><i style={{width:`${Math.max(value*100,0.3)}%`}}/></div><strong>{pct(value)}</strong></div>)}</div>}{knots&&<><h3>Cumulative distribution</h3><svg className="cdf" viewBox="0 0 500 160" role="img" aria-label="Saved cumulative probability distribution"><line x1="20" y1="140" x2="480" y2="140" stroke="#ccd5cd"/><line x1="20" y1="10" x2="20" y2="140" stroke="#ccd5cd"/><polyline fill="none" stroke="#3d7057" strokeWidth="3" points={knots.map(([x,y])=>`${20+((x-knots[0][0])/(knots[knots.length-1][0]-knots[0][0]||1))*460},${140-y*130}`).join(' ')}/><text x="20" y="157">{knots[0][0].toFixed(2)}</text><text x="440" y="157">{knots[knots.length-1][0].toFixed(2)}</text></svg><p className="subtle">X: saved numeric support · Y: cumulative probability. Units follow the question rules.</p></>}<details className="raw"><summary>View structured forecast</summary><pre>{JSON.stringify(f,null,2)}</pre></details></>;}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
