import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowLeft, ArrowRight, Search, Check, Clock3, FileText, Layers3, ChevronRight, ExternalLink, Download, AlertCircle, Radio, Fingerprint, BookOpen, GitBranch, LayoutGrid, List, Landmark, TrendingUp, Cpu, Globe2, Rocket } from 'lucide-react';
import './style.css';
import './market.css';
import { validKnots, quantile, formatValue } from './distribution';

type Stage = {id:string;title:string;status:string;count:number};
type Source = {id:string;url:string;title:string;characters:number;body_sha256:string;captured_at:string|null;excerpt:string;excerpt_truncated:boolean;supplemented:boolean};
type Task = {id:string;title:string;type:string;status:string;created_at:string|null;rules:string;fine_print:string;run_id:string;run_url:string;question_url:string;input_sha256:string;record_scope:string;warning:string;stages:Stage[];plan:{id:string;condition:string;priority:string;query:string}[];searches:{channel:string;query:string;role:string;status:string;results:{url:string;title:string;snippet:string}[]}[];sources:Source[];fetches:{url:string;status:string;error:string}[];supplement:{tool:string;url:string;status:string;error:string}[];forecast:Record<string,unknown>;analysis:{model:string;status:string;routing:Record<string,unknown>;gaps:unknown[];first_probability_yes:number|null};delivery:{status:string;note:string};usage:Record<string,number|null>};
type Data = {release:string;release_commit:string;generated_at:string;notice:string;tasks:Task[]};
const names:Record<string,string>={binary:'Binary',numeric:'Numeric',multiple_choice:'Multiple choice',discrete:'Discrete',date:'Date'};
const human=(v:string)=>v.replaceAll('_',' ');
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;
const category=(t:Task)=>/prime minister|president|ceasefire|government|election|withdrawal|armed forces|lebanon|pope|court/i.test(t.title)?'Politics':/gas price|housing|payroll|earnings|inflation|unemployment/i.test(t.title)?'Economics':/capitalization|stock|public company|trading|spacex/i.test(t.title)?'Finance':'Tech & Science';
const categoryIcons:Record<string,typeof Landmark>={'Politics':Landmark,'Economics':TrendingUp,'Finance':Rocket,'Tech & Science':Cpu};
function unit(t:Task){const text=t.title+' '+t.rules;return /dollars per gallon/i.test(text)?'USD / gallon':/thousands of units/i.test(text)?'thousand units':'';}
function summary(t:Task){const p=t.forecast.probability_yes;if(typeof p==='number')return pct(p)+' YES';const bins=t.forecast.option_probabilities||t.forecast.probabilities;if(bins&&typeof bins==='object'){const sorted=Object.entries(bins as Record<string,number>).sort((a,b)=>b[1]-a[1]);return sorted.length?`${pct(sorted[0][1])} · ${sorted[0][0]}`:'Distribution';}const k=validKnots(t.forecast.cdf_knots);if(k)return formatValue(quantile(k,.5),t.type)+(unit(t)?' '+unit(t):'');return Object.keys(t.forecast).length?'Forecast recorded':'No forecast';}
function download(data:unknown,name:string){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
function Badge({value}:{value:string}){return <span className={`badge ${value.includes('gap')?'amber':value==='not_recorded'?'muted':'green'}`}><span/> {human(value)}</span>;}
function App(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(new URLSearchParams(location.search).get('question')),[view,setView]=useState('Research'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[stage,setStage]=useState('rules'),[topic,setTopic]=useState('All'),[layout,setLayout]=useState('cards'),[sort,setSort]=useState('default');
 useEffect(()=>{fetch(`${import.meta.env?.BASE_URL || '/'}data/console.json`).then(r=>{if(!r.ok)throw Error('Snapshot could not be loaded');return r.json();}).then(setData).catch(e=>setError(e.message));},[]);
 useEffect(()=>{const onPop=()=>setSelected(new URLSearchParams(location.search).get('question'));window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
 function open(id:string|null){setSelected(id);setStage('rules');const u=new URL(location.href);id?u.searchParams.set('question',id):u.searchParams.delete('question');history.pushState({},'',u);window.scrollTo(0,0);}
 if(error)return <div className="load"><AlertCircle/><h1>Snapshot unavailable</h1><p>{error}</p><button onClick={()=>location.reload()}>Retry</button></div>;
 if(!data)return <div className="load"><Layers3/><p>Loading the research archive…</p></div>;
 const task=data.tasks.find(t=>t.id===selected);const tasks=data.tasks.filter(t=>(filter==='all'||t.type===filter)&&(topic==='All'||category(t)===topic)&&(t.title+' '+t.id).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='sources'?b.sources.length-a.sources.length:sort==='title'?a.title.localeCompare(b.title):0);
 return <><header className="header"><a className="brand" href="?" onClick={e=>{e.preventDefault();open(null);}}><span className="brand-icon"><Layers3 size={21}/></span>Forecast<span>Agent</span><small>RESEARCH CONSOLE</small></a><nav>{['Overview','Research','Activity'].map(v=><button key={v} className={view===v&&!task?'active':''} onClick={()=>{setView(v);open(null);}}>{v}</button>)}</nav><div className="header-right"><span className="release"><GitBranch size={13}/>v{data.release}</span><a href="https://github.com/chenencc/futureeval-forecasting-agent" target="_blank" rel="noreferrer">Repository <ArrowUpRight size={15}/></a></div></header>
 <div className="archive-bar"><span><Radio size={13}/> ARCHIVED SNAPSHOT</span><p>Real research records. Read-only preview · no live submission controls.</p><time>{new Date(data.generated_at).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</time></div>
 {task?<main className="detail"><button className="back" onClick={()=>open(null)}><ArrowLeft size={15}/> All research</button><div className="detail-heading"><div><div className="eyebrow">METACULUS / {names[task.type]||task.type} / #{task.id}</div><h1>{task.title}</h1><div className="heading-meta"><Badge value={task.status}/><span>Run {task.run_id}</span><a href={task.question_url} target="_blank" rel="noreferrer">Original question <ArrowUpRight size={14}/></a></div></div><button className="outline" onClick={()=>download(task,`question-${task.id}.json`)}><Download size={15}/> Export record</button></div>
 <div className="detail-grid"><aside className="steps"><div className="eyebrow">RESEARCH TRAIL</div>{task.stages.map((s,i)=><button key={s.id} onClick={()=>setStage(s.id)} className={stage===s.id?'selected':''}><span className={`step-icon ${s.status==='not_recorded'?'empty':''}`}>{s.status==='not_recorded'?<Clock3 size={13}/>:<Check size={13}/>}</span><span><small>0{i+1}</small>{s.title}</span><ChevronRight size={13}/></button>)}<div className="trail-note"><Fingerprint size={16}/><p>Every displayed source is linked to a saved body hash. A saved page is not a verified fact.</p></div></aside>
 <section className="stage-panel"><div className="panel-heading"><span className="eyebrow">STEP 0{task.stages.findIndex(s=>s.id===stage)+1}</span><Badge value={task.stages.find(s=>s.id===stage)!.status}/><h2>{task.stages.find(s=>s.id===stage)!.title}</h2></div>
 {stage==='rules'&&<><h3>Resolution criteria</h3><p className="prose">{task.rules}</p>{task.fine_print&&<><h3>Fine print</h3><p className="prose">{task.fine_print}</p></>}<div className="callout"><BookOpen size={18}/><p>The target event, observation date and resolution source belong to the question rules. Capture dates and publication dates are separate.</p></div></>}
 {stage==='plan'&&<>{task.plan.length?task.plan.map((p,i)=><article className="item" key={i}><div><span className="mono">NEED {p.id}</span><span className="tag">{p.priority||'Unspecified'}</span></div><h3>{p.condition}</h3>{p.query&&<p className="quote">{p.query}</p>}</article>):<Empty/>}</>}
 {stage==='search'&&<>{task.searches.length?task.searches.map((s,i)=><article className="item" key={i}><div><span className="tag">{s.channel}</span><Badge value={s.status}/></div><h3>{s.query}</h3><p className="subtle">Search role: {s.role} · {s.results.length} saved results</p>{s.results.map((r,j)=><a className="search-hit" key={j} href={r.url} target="_blank" rel="noreferrer"><span>{r.title||r.url}<ExternalLink size={12}/></span><small>{r.snippet}</small></a>)}</article>):<Empty/>}</>}
 {stage==='read'&&<><p className="subtle">{task.sources.length} saved bodies. Previews are bounded; omissions do not prove absence.</p>{task.sources.map(s=><SourceCard key={s.id} source={s}/>)}<h3>Fetch journal</h3>{task.fetches.map((f,i)=><div className="journal" key={i}><span>{f.url||'URL not recorded'}</span><Badge value={f.status}/>{f.error&&<p>{f.error}</p>}</div>)}</>}
 {stage==='supplement'&&<>{task.supplement.length?task.supplement.map((s,i)=><div className="journal" key={i}><span>{s.tool} · {s.url||'No URL recorded'}</span><Badge value={s.status||'unknown'}/>{s.error&&<p>{s.error}</p>}</div>):<Empty text="Supplement lineage exists in some archives, but no per-attempt journal is present in this export."/>}<p className="subtle">Supplemented bodies remain available in Read original sources.</p></>}
 {stage==='analysis'&&<><div className="model-card"><span className="brand-icon"><Layers3 size={20}/></span><div><strong>Mercury Decide</strong><p>{task.analysis.model}</p></div><Badge value={task.analysis.status}/></div><h3>Conditional rereading</h3><p className="prose">{task.analysis.routing.second_call_required?'A second decision was requested after reading additional saved original evidence.':'No second-call requirement is recorded.'}</p><pre>{JSON.stringify(task.analysis.routing,null,2)}</pre><h3>Remaining diagnostic gaps</h3>{task.analysis.gaps.length?<div className="gap-list">{task.analysis.gaps.map((g,i)=><span key={i}><AlertCircle size={14}/>{typeof g==='string'?human(g):JSON.stringify(g)}</span>)}</div>:<p className="subtle">No diagnostic gaps recorded. This does not establish factual correctness.</p>}</>}
 {stage==='forecast'&&<Forecast task={task}/>}
 {stage==='delivery'&&<><Empty text={task.delivery.note}/><div className="callout"><AlertCircle size={18}/><p>An analysis result is not a submission receipt. These archived experiments are not displayed as delivered forecasts.</p></div></>}
 </section><aside className="facts"><div className="fact-card"><div className="eyebrow">{validKnots(task.forecast.cdf_knots)?'PREDICTED MEDIAN':'SAVED FORECAST'}</div><strong className="forecast-number">{summary(task)}</strong><span className="subtle">{names[task.type]||task.type} · archived decision</span><button onClick={()=>setStage('forecast')}>Explore distribution <ArrowRight size={14}/></button></div><div className="fact-card"><div className="eyebrow">RESOURCE JOURNAL</div><dl><dt>Search attempts</dt><dd>{task.usage.search_attempts}</dd><dt>Fetch attempts</dt><dd>{task.usage.fetch_attempts}</dd><dt>Acquisition model HTTP</dt><dd>{task.usage.acquisition_http_attempts}</dd><dt>Reported tokens</dt><dd>Not exported</dd></dl></div><div className="fact-card"><div className="eyebrow">PROVENANCE</div><a href={task.run_url} target="_blank" rel="noreferrer">Actions run <ArrowUpRight size={14}/></a><p className="subtle">{task.record_scope}</p><span className="mono hash">INPUT SHA256<br/>{task.input_sha256}</span></div></aside></div></main> :<main className="landing market-page">
 <div className="market-heading"><div><h1>{view==='Activity'?'Research activity':topic==='All'?'Research markets':`${topic} markets`}</h1><p>Source-linked forecasts. Every decision, with its research trail.</p></div><span className="snapshot-pill"><Clock3 size={15}/> Archived preview</span></div>
 <div className="category-nav" aria-label="Research categories">{['All','Politics','Economics','Finance','Tech & Science'].map(c=><button key={c} className={topic===c?'selected':''} onClick={()=>{setTopic(c);setFilter('all');}}>{c==='All'?<Globe2 size={17}/>:React.createElement(categoryIcons[c],{size:17})}{c}<span>{c==='All'?data.tasks.length:data.tasks.filter(t=>category(t)===c).length}</span></button>)}</div>
 <div className="collection-banner"><span className="banner-icon"><Layers3 size={25}/></span><div><strong>Follow a forecast from first search to final decision</strong><p>Original acquisition → independent supplement → Mercury rereading → forecast</p></div><button onClick={()=>open(data.tasks.find(t=>topic==='All'||category(t)===topic)?.id||data.tasks[0].id)}>Explore a trail <ArrowUpRight size={18}/></button></div>
 <div className="type-tags"><span>Question type</span>{['all','binary','numeric','multiple_choice','discrete','date'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f==='all'?'All types':names[f]}</button>)}</div>
 {view==='Activity'?<section className="research"><h2>Saved executions</h2>{tasks.map(t=><div className="activity" key={t.id}><span className="step-icon"><FileText size={18}/></span><div><strong>{t.title}</strong><p>#{t.id} · Run {t.run_id} · {t.created_at||'Capture time not recorded'}</p></div><a href={t.run_url} target="_blank" rel="noreferrer">View run <ArrowUpRight size={16}/></a></div>)}</section>:<>
 <div className="market-controls"><label className="search"><Search size={20}/><input aria-label="Search questions" placeholder="Search questions or ID" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="control-right"><label className="sort-control">Sort <select aria-label="Sort questions" value={sort} onChange={e=>setSort(e.target.value)}><option value="default">Snapshot order</option><option value="sources">Most evidence</option><option value="title">Title A–Z</option></select></label><div className="view-toggle"><button aria-pressed={layout==='cards'} className={layout==='cards'?'selected':''} onClick={()=>setLayout('cards')}><LayoutGrid size={17}/> Cards</button><button aria-pressed={layout==='table'} className={layout==='table'?'selected':''} onClick={()=>setLayout('table')}><List size={17}/> Table</button></div></div></div>
 <div className="market-section-title"><h2>Archived questions <span>({tasks.length})</span></h2><button className="text-button" onClick={()=>download(data,'forecastagent-export.json')}><Download size={17}/> Export snapshot</button></div>
 {layout==='cards'?<div className="market-grid">{tasks.map(t=><MarketCard key={t.id} task={t} open={()=>open(t.id)}/>)}</div>:<div className="table-view"><div className="table-head"><span>QUESTION</span><span>SOURCES</span><span>MODEL FORECAST</span><span>STATUS</span></div>{tasks.map(t=><button className="question-row" key={t.id} onClick={()=>open(t.id)}><div><small>{category(t)} · {names[t.type]} · #{t.id}</small><h3>{t.title}</h3></div><div className="row-source"><FileText size={16}/>{t.sources.length}<small>{t.searches.length} searches</small></div><strong className="row-forecast">{summary(t)}</strong><div><Badge value={t.status}/><ArrowUpRight size={19}/></div></button>)}</div>}
 {!tasks.length&&<Empty text="No archived questions match this category and filter."/>}
 <div className="library-note"><Fingerprint size={18}/><p>Showing saved research, not live market quotes. Unrecorded prices and submission receipts stay unrecorded.</p><span>v{data.release}</span></div>
 </>}
 </main>}

 <footer><div className="brand"><Layers3 size={19}/>ForecastAgent</div><p>Evidence first. Uncertainty visible.</p><span>Archived preview · {data.tasks.length} questions · v{data.release}</span></footer></>;
}
function MarketCard({task:t,open}:{task:Task;open:()=>void}){const cat=category(t),Icon=categoryIcons[cat],p=t.forecast.probability_yes;
 const options=t.forecast.option_probabilities||t.forecast.probabilities;const choices=options?Object.entries(options as Record<string,number>).sort((a,b)=>b[1]-a[1]).slice(0,2):[];

 return <article className="market-card"><button className="card-main" onClick={open} aria-label={`Open question ${t.id}: ${t.title}`}><div className="card-top"><span className={`topic-icon topic-${cat.split(' ')[0].toLowerCase()}`}><Icon size={24}/></span><div><span className="card-category">{cat}</span><span className="card-platform">Metaculus · #{t.id}</span></div><ArrowUpRight size={18}/></div><h3>{t.title}</h3><div className="card-type">{names[t.type]}<span>Mercury Decide</span></div>
 {typeof p==='number'?<><div className="card-outcome"><span>Yes</span><div><small>Model</small><strong>{pct(p)}</strong></div></div><div className="card-probability"><span style={{width:`${p*100}%`}}/></div></>:choices.length?<div className="card-options">{choices.map(([label,value])=><div className="card-outcome" key={label}><span>{label}</span><div><small>Model</small><strong>{pct(value)}</strong></div></div>)}</div>:<DistributionPreview task={t}/> }
 <div className="market-price-note"><span>Market price</span><span>Not recorded</span></div></button><div className="card-footer"><span><FileText size={15}/>{t.sources.length} sources</span><span className="gap-indicator"><AlertCircle size={14}/>{t.analysis.gaps.length} gaps</span><button onClick={open}>Research <ArrowRight size={15}/></button></div></article>;
}
function Empty({text='No record is available for this stage.'}:{text?:string}){return <div className="empty-state"><Clock3 size={24}/><h3>Not recorded</h3><p>{text}</p></div>;}
function SourceCard({source:s}:{source:Source}){return <details className="source-card"><summary><span className="source-id">{s.id}</span><div><strong>{s.title}</strong><small>{s.characters.toLocaleString()} characters · {s.supplemented?'supplemented':'saved body'}</small></div><ChevronRight size={16}/></summary><div className="source-content"><a href={s.url} target="_blank" rel="noreferrer">Open publisher page <ExternalLink size={13}/></a><p className="subtle">Capture time: {s.captured_at||'Not recorded'} · Current page may differ from the snapshot.</p><pre>{s.excerpt}</pre>{s.excerpt_truncated&&<p className="subtle">Preview truncated at 1,800 characters. The saved body is longer.</p>}<div className="hash mono">BODY SHA256 · {s.body_sha256}</div></div></details>;}
function Forecast({task:t}:{task:Task}){const f=t.forecast;const p=f.probability_yes;const choices=(f.option_probabilities||f.probabilities) as Record<string,number>|undefined;const knots=f.cdf_knots as [number,number][]|undefined;return <><div className="forecast-display"><span className="eyebrow">{knots?'PREDICTED MEDIAN':'ARCHIVED FORECAST'} · {names[t.type]}</span><strong>{summary(t)}</strong><p>Saved model forecast. Values below describe its uncertainty, not an observed outcome.</p></div>{typeof p==='number'&&<><div className="probability-track"><span style={{width:`${p*100}%`}}/></div><div className="probability-label"><span>YES {pct(p)}</span><span>NO {pct(1-p)}</span></div></>}{choices&&<div className="distribution">{Object.entries(choices).map(([label,value])=><div key={label}><span>{label}</span><div><i style={{width:`${Math.max(value*100,0.3)}%`}}/></div><strong>{pct(value)}</strong></div>)}</div>}{knots&&<DistributionChart task={t}/>}<details className="raw"><summary>View structured forecast</summary><pre>{JSON.stringify(f,null,2)}</pre></details></>;}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
function DistributionPreview({task:t}:{task:Task}){const k=validKnots(t.forecast.cdf_knots);if(!k)return <p>No readable distribution recorded</p>;return <div className="distribution-preview"><span>Predicted median</span><strong>{formatValue(quantile(k,.5),t.type)}</strong>{unit(t)&&<span>{unit(t)}</span>}<p>50% probability range</p><b>{formatValue(quantile(k,.25),t.type)} – {formatValue(quantile(k,.75),t.type)}</b><small>Approximate · from saved forecast bins</small></div>;}
function DistributionChart({task:t}:{task:Task}){
 const [cumulative,setCumulative]=useState(false);const k=validKnots(t.forecast.cdf_knots);if(!k)return <Empty text="Saved distribution cannot be plotted safely."/>;
 const min=k[0][0],max=k[k.length-1][0],x=(v:number)=>50+(v-min)/(max-min)*490;
 const bins=k.slice(1).map(([b,p],i)=>({a:k[i][0],b,mass:p-k[i][1]})),peak=Math.max(...bins.map(b=>b.mass),.001),y=(v:number)=>175-v/(cumulative?1:peak)*135;
 const q=[.25,.5,.75].map(p=>({p,value:quantile(k,p)}));
 return <div className="readable-distribution"><div className="distribution-heading"><h3>Forecast distribution{unit(t)&&<small className="chart-unit"> · {unit(t)}</small>}</h3><div className="view-toggle"><button aria-pressed={!cumulative} onClick={()=>setCumulative(false)}>Probability</button><button aria-pressed={cumulative} onClick={()=>setCumulative(true)}>Cumulative</button></div></div><p className="subtle">{cumulative?'Chance the outcome is at or below each value.':'Each bar shows the probability assigned to a saved value interval.'}</p><svg viewBox="0 0 600 225" role="img" aria-label={cumulative?'Cumulative probability with median and quartile markers':'Probability by saved interval with median and quartile markers'}>
 {[0,.5,1].map(v=><g key={v}><line x1="50" x2="540" y1={175-v*135} y2={175-v*135} stroke="#e7ece9"/><text x="40" y={180-v*135} textAnchor="end">{pct(v*(cumulative?1:peak))}</text></g>)}
 {!cumulative&&bins.map((b,i)=><rect key={i} x={x(b.a)+1} y={y(b.mass)} width={Math.max(x(b.b)-x(b.a)-2,1)} height={175-y(b.mass)} fill="#9bc5ab"><title>{formatValue(b.a,t.type)} – {formatValue(b.b,t.type)}: {pct(b.mass)}</title></rect>)}
 {cumulative&&<polyline fill="none" stroke="#397357" strokeWidth="3" points={k.map(([v,p])=>`${x(v)},${y(p)}`).join(' ')}/>}
 {q.map(({p,value})=>value!==null&&<g key={p}><line x1={x(value)} x2={x(value)} y1="32" y2="175" stroke="#426f56" strokeDasharray="4 4"/><text x={x(value)} y={p===.5?19:31} textAnchor="middle">{p===.5?'Median':pct(p)}</text></g>)}
 {[0,.5,1].map(v=><text key={v} x={50+v*490} y="202" textAnchor={v===0?'start':v===1?'end':'middle'}>{formatValue(min+(max-min)*v,t.type)}</text>)}
 </svg><div className="quantile-table">{q.map(({p,value})=><div key={p}><span>{p===.5?'Predicted median':p===.25?'Lower quartile (25%)':'Upper quartile (75%)'}</span><strong>{formatValue(value,t.type)}</strong></div>)}</div><p className="interval-explanation">50% probability range: {formatValue(q[0].value,t.type)} – {formatValue(q[2].value,t.type)}.</p><div className="tail-probabilities"><span>Below {formatValue(min,t.type)}: <b>{pct(k[0][1])}</b></span><span>Above {formatValue(max,t.type)}: <b>{pct(1-k[k.length-1][1])}</b></span></div><p className="subtle">Quartiles are approximate, interpolated within saved bins. Bars preserve the original interval probabilities. Numeric units follow the question wording. Dates use UTC.</p><a className="subtle" href="https://www.metaculus.com/faq/#how-do-i-use-the-range-interface" target="_blank" rel="noreferrer">How to read a forecast distribution ↗</a></div>;
}
