"""Separate productive decisions from bounded transport failures."""
MODEL_DECISIONS_PER_DISPATCH = 12
MODEL_FAILURES_PER_DISPATCH = 4
MODEL_HTTP_PER_DISPATCH = MODEL_DECISIONS_PER_DISPATCH + MODEL_FAILURES_PER_DISPATCH
