"""Source contracts describe coverage and limitations, not factual confidence."""

SOURCES = {
    "congress_bill": dict(domain="politics", role="official_legislation_detail", format="json", endpoint="https://api.congress.gov/v3/bill/{congress}/{bill_type}/{bill_number}", defaults={"format":"json"}, parameters={"congress":"Exact Congress number, e.g. 119", "bill_type":"hr, s, hjres, sjres, hconres, sconres, hres or sres", "bill_number":"Exact positive bill number"}, path_parameters=["congress","bill_type","bill_number"], requires_configuration=["CONGRESS_API_KEY"], requires_key=True, records="congress_bill", docs="https://github.com/LibraryOfCongress/api.congress.gov/blob/main/Documentation/BillEndpoint.md", caveat="Retain latestAction, laws and introducedDate separately. Title or a passed chamber does not establish enactment or commencement."),
    "congress_actions": dict(domain="politics", role="official_legislative_actions", format="json", endpoint="https://api.congress.gov/v3/bill/{congress}/{bill_type}/{bill_number}/actions", defaults={"format":"json","limit":20,"offset":0}, parameters={"congress":"Exact Congress number", "bill_type":"Exact lowercase bill type", "bill_number":"Exact positive bill number", "limit":"Page size 1..250", "offset":"Explicit offset 0..100000"}, path_parameters=["congress","bill_type","bill_number"], requires_configuration=["CONGRESS_API_KEY"], requires_key=True, records="congress_actions", docs="https://github.com/LibraryOfCongress/api.congress.gov/blob/main/Documentation/BillEndpoint.md", caveat="Preserve actionDate, text, sourceSystem and recorded votes. One page is not a complete legislative history; do not infer enactment from action codes alone."),
    "congress_texts": dict(domain="politics", role="official_bill_text_index", format="json", endpoint="https://api.congress.gov/v3/bill/{congress}/{bill_type}/{bill_number}/text", defaults={"format":"json","limit":20,"offset":0}, parameters={"congress":"Exact Congress number", "bill_type":"Exact lowercase bill type", "bill_number":"Exact positive bill number", "limit":"Page size 1..250", "offset":"Explicit offset 0..100000"}, path_parameters=["congress","bill_type","bill_number"], requires_configuration=["CONGRESS_API_KEY"], requires_key=True, records="congress_texts", docs="https://github.com/LibraryOfCongress/api.congress.gov/blob/main/Documentation/BillEndpoint.md", caveat="Text index is not full text. Preserve version type, date and formats. Select an original format with intelligence_bill_text; enrolled text alone is not proof of signed law."),
    "worldbank": dict(domain="finance", role="official_statistics", format="json", endpoint="https://api.worldbank.org/v2/country/{country}/indicator/{indicator}", defaults={"format":"json", "per_page":20}, parameters={"country":"ISO country code", "indicator":"Exact indicator code", "date":"Year or year range"}, path_parameters=["country", "indicator"], records="worldbank", docs="https://datahelpdesk.worldbank.org/knowledgebase/articles/889392", caveat="Annual, revised data. Observation year is not a historical publication vintage."),
    "fred_csv": dict(domain="finance", role="official_statistics", format="csv", endpoint="https://fred.stlouisfed.org/graph/fredgraph.csv", defaults={}, parameters={"id":"Exact FRED series ID", "cosd":"Start date YYYY-MM-DD", "coed":"End date YYYY-MM-DD"}, records="csv", docs="https://fred.stlouisfed.org/", caveat="Public graph CSV export, not vintage API. Revised series and export availability can change."),
    "fed_news": dict(domain="finance", role="official_announcement", format="feed", endpoint="https://www.federalreserve.gov/feeds/press_all.xml", defaults={}, parameters={}, records="feed", docs="https://www.federalreserve.gov/feeds/feeds.htm", caveat="Announcement leads and summaries; follow original links for full text."),
    "federal_register": dict(domain="politics", role="official_registry", format="json", endpoint="https://www.federalregister.gov/api/v1/documents.json", defaults={"per_page":5,"order":"newest"}, parameters={"conditions[term]":"Search phrase", "conditions[publication_date][gte]":"Earliest publication date", "conditions[publication_date][lte]":"Latest publication date"}, records="results", docs="https://www.federalregister.gov/developers/documentation/api/v1", caveat="Preserve document type and effective date. Proposed rules are not enacted laws; verify official linked PDF."),
    "uk_bills": dict(domain="politics", role="official_legislation", format="json", endpoint="https://bills-api.parliament.uk/api/v1/Bills", defaults={"Take":5}, parameters={"SearchTerm":"Bill search phrase"}, records="items", docs="https://bills-api.parliament.uk/index.html", caveat="A bill record is not proof of Royal Assent; inspect stage and detail links."),
    "clinical_trials": dict(domain="health", role="official_registry", format="json", endpoint="https://clinicaltrials.gov/api/v2/studies", defaults={"pageSize":5,"format":"json","countTotal":"true"}, parameters={"query.term":"Study or intervention query", "query.id":"Exact NCT identifier"}, records="studies", docs="https://clinicaltrials.gov/data-api/api", caveat="Registry entries are sponsor reports, not independent evidence of efficacy."),
    "usgs": dict(domain="environment", role="official_observation", format="json", endpoint="https://earthquake.usgs.gov/fdsnws/event/1/query", defaults={"format":"geojson","limit":5,"orderby":"time"}, parameters={"starttime":"Inclusive event start UTC", "endtime":"Event end UTC", "minmagnitude":"Minimum magnitude"}, records="features", docs="https://earthquake.usgs.gov/fdsnws/event/1/", caveat="Magnitude and event status can be revised. Preserve geometry and event time."),
    "nasa_eonet": dict(domain="environment", role="official_aggregation", format="json", endpoint="https://eonet.gsfc.nasa.gov/api/v3/events", defaults={"limit":5,"status":"open"}, parameters={"category":"Event category", "start":"Start date", "end":"End date"}, records="events", docs="https://eonet.gsfc.nasa.gov/docs/v3", caveat="Aggregated natural events; retain original source links and geometry dates."),
    "crossref": dict(domain="science", role="bibliographic_metadata", format="json", endpoint="https://api.crossref.org/works", defaults={"rows":5}, parameters={"query":"Research search phrase", "filter":"Crossref filter expression"}, records="crossref", docs="https://www.crossref.org/documentation/retrieve-metadata/rest-api/", caveat="Publication metadata and abstracts where present; not paper full text or validated findings."),
    "sec_concept": dict(domain="finance",role="issuer_xbrl",format="json",endpoint="https://data.sec.gov/api/xbrl/companyconcept/CIK{cik}/{taxonomy}/{tag}.json",defaults={},parameters={"cik":"Exact ten-digit issuer CIK", "taxonomy":"us-gaap, ifrs-full, dei or srt", "tag":"Exact XBRL concept tag"},path_parameters=["cik","taxonomy","tag"],requires_configuration=["SEC_USER_AGENT"],records="sec_concept",docs="https://www.sec.gov/search-filings/edgar-application-programming-interfaces",caveat="Facts retain units, period start/end, filed date, form and accession. Quarterly and year-to-date facts must not be interchanged; issuer-specific non-GAAP metrics may not be present."),
    "sec_submissions": dict(domain="finance",role="issuer_filings",format="json",endpoint="https://data.sec.gov/submissions/CIK{cik}.json",defaults={},parameters={"cik":"Exact ten-digit issuer CIK"},path_parameters=["cik"],requires_configuration=["SEC_USER_AGENT"],records="sec_submissions",docs="https://www.sec.gov/search-filings/edgar-application-programming-interfaces",caveat="Recent filings are a bounded columnar window. Additional historical files are separate; filing acceptance is not an earnings result."),
    "uk_bill_detail": dict(domain="politics",role="official_legislation_detail",format="json",endpoint="https://bills-api.parliament.uk/api/v1/Bills/{bill_id}",defaults={},parameters={"bill_id":"Exact integer bill ID"},path_parameters=["bill_id"],records="object",identity_field="billId",identity_parameter="bill_id",docs="https://bills-api.parliament.uk/",caveat="Bill detail and current stage do not prove enactment or commencement. Preserve isAct and stage independently."),
    "uk_bill_publications": dict(domain="politics",role="official_bill_text_index",format="json",endpoint="https://bills-api.parliament.uk/api/v1/Bills/{bill_id}/Publications",defaults={},parameters={"bill_id":"Exact integer bill ID"},path_parameters=["bill_id"],records="publications",identity_field="billId",identity_parameter="bill_id",docs="https://bills-api.parliament.uk/",caveat="Publications include correspondence and explanatory notes; choose the exact bill text and stage, then read its linked document."),
    "federal_register_detail": dict(domain="politics",role="official_regulatory_detail",format="json",endpoint="https://www.federalregister.gov/api/v1/documents/{document_number}.json",defaults={},parameters={"document_number":"Exact Federal Register YYYY-NNNNN identifier"},path_parameters=["document_number"],records="object",identity_field="document_number",identity_parameter="document_number",docs="https://www.federalregister.gov/developers/documentation/api/v1",caveat="Preserve type, publication and effective dates separately. Use original text/PDF; an effective date does not prove all provisions commenced."),
    "uk_legislation_xml": dict(domain="politics",role="official_statute_text",format="clml",endpoint="https://www.legislation.gov.uk/{type}/{year}/{number}/data.xml",defaults={},parameters={"type":"ukpga, uksi, ukla, asp, asc, anaw, mnia, nia or nisr", "year":"Enactment year", "number":"Act or instrument number", "version":"enacted, made, a YYYY-MM-DD snapshot, or omit for latest"},path_parameters=["type","year","number"],records="clml",docs="https://legislation.github.io/data-documentation/api/overview.html",caveat="Latest revised text is not an as-enacted or historical publication snapshot. Preserve document URI, provision IDs and changes/commencement warnings."),
}

from .public_channels import CHANNELS
SOURCES.update(CHANNELS)

KEY_REQUIREMENTS = [
    dict(id="fred_api", domain="finance", secret="FRED_API_KEY", url="https://fred.stlouisfed.org/docs/api/api_key.html", purpose="Full API and ALFRED vintage observations", implemented=False),
    dict(id="congress", domain="politics", secret="CONGRESS_API_KEY", url="https://api.congress.gov/sign-up/", purpose="US bill detail, actions and original text versions", implemented=True),
    dict(id="fec", domain="politics", secret="FEC_API_KEY", url="https://api.open.fec.gov/developers/", purpose="US campaign finance", implemented=False),
    dict(id="sec", domain="finance", secret=None, configuration="SEC_USER_AGENT", url="https://www.sec.gov/search-filings/edgar-application-programming-interfaces", purpose="Issuer filings and XBRL; identifying contact User-Agent, no API key", implemented=True),
]


def catalog(domain=None):
    from .profiles import PROFILES
    from .discovery import ROUTES
    return {"version":"intelligence_catalog_v1", "sources":[dict(id=k, **{"requires_key":False, **v}) for k,v in SOURCES.items() if domain is None or v["domain"] == domain], "document_profiles":[dict(id=k,**v) for k,v in PROFILES.items() if domain is None or v["domain"]==domain], "discovery_routes":[dict(r) for r in ROUTES if domain is None or r['domain']==domain], "optional_onboarding":KEY_REQUIREMENTS}
